
name: Gymapp Deployment CI

on: [push]

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest
    
    steps:
      
      - name: Git checkout
        uses: actions/checkout@v1
        
      - name: Listing Branch and Ref
        run: |
          echo running on branch ${GITHUB_REF##*/}
          echo ref context is ${{github.ref}}
        
      - name: Building Docker Image
        run: docker build -t docker.pkg.github.com/captain-svxn/gymapp/ci-deploy:${GITHUB_REF##*/} .
      
      - name: Login to GitHub Docker Registry
        run: docker login docker.pkg.github.com --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.GITHUB_DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push Docker Image to GitHub Docker Registry
        run: docker push docker.pkg.github.com/captain-svxn/gymapp/ci-deploy:${GITHUB_REF##*/}
        
      - name: Deploying Master to K8S Cluster
        uses: appleboy/ssh-action@master
        if: github.ref == 'refs/heads/master'
        with:
          host: ${{ secrets.K8S_HOST }}
          username: ${{ secrets.K8S_USERNAME }}
          password: ${{ secrets.K8S_PASSWORD }}
          port: ${{ secrets.K8S_PORT }}
          script: kubectl rollout restart deployment gymapp -n gymapp
  
      - name: Deploying Beta to K8S Cluster
        uses: appleboy/ssh-action@master
        if: github.ref == 'refs/heads/beta'
        with:
          host: ${{ secrets.K8S_HOST }}
          username: ${{ secrets.K8S_USERNAME }}
          password: ${{ secrets.K8S_PASSWORD }}
          port: ${{ secrets.K8S_PORT }}
          script: kubectl rollout restart deployment gymapp-beta -n gymapp





