name: Docker Image und Deployment CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
      
      - name: Git checkout
        uses: actions/checkout@v1
        
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
        
      - name: Build
        run: docker build -t docker.pkg.github.com/captain-svxn/gymapp:${GITHUB_REF##*/} .
      
      - name: Login to GitHub Docker Registry
        run: docker login docker.pkg.github.com --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.GITHUB_DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_DOCKER_PASSWORD }}
      
      - name: Push to GitHub Docker Registry
        run: docker push docker.pkg.github.com/captain-svxn/gymapp/ci-deploy:${GITHUB_REF##*/}
      
