name: Gymapp Deployment CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
      
      - name: Git checkout
        uses: actions/checkout@v1
        
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
        
      - name: Build
        run: docker build -t docker.pkg.github.com/captain-svxn/gymapp/ci-deploy:${GITHUB_REF##*/} .
      
      - name: Login to GitHub Docker Registry
        run: docker login docker.pkg.github.com --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.GITHUB_DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push to GitHub Docker Registry
        run: docker push docker.pkg.github.com/captain-svxn/gymapp/ci-deploy:${GITHUB_REF##*/}
        
      - name: Deploy Master to K8S Cluster
        uses: appleboy/ssh-action@master
        if: GITHUB_REF##*/ == master
        with:
          host: ${{ secrets.K8S_HOST }}
          username: ${{ secrets.K8S_USERNAME }}
          password: ${{ secrets.K8S_PASSWORD }}
          port: ${{ secrets.K8S_PORT }}
          script: kubectl rollout restart deployment gymapp -n gymapp
        
      - name: Deploy Beta to K8S Cluster
        uses: appleboy/ssh-action@master
        if: GITHUB_REF##*/ == beta
        with:
          host: ${{ secrets.K8S_HOST }}
          username: ${{ secrets.K8S_USERNAME }}
          password: ${{ secrets.K8S_PASSWORD }}
          port: ${{ secrets.K8S_PORT }}
          script: kubectl rollout restart deployment gymapp-beta -n gymapp




